language: python
python:
  - "3.6.1"
install:
  - pip install -r requirements.txt
  - createdb bucketlist_test
  - createdb bucketlist
  - python manage.py db migrate
env:
  - DB=postgres
addons:
  postgresql: "9.4"
script:
  - nosetests --with-coverage --cover-package=app.api
notifications:
  slack: andela:yvkk8NOcfPJkZQTqITrEsnsm
after_success:
  coveralls
