language: python
python:
  - "3.6.1"
install:
  - pip install -r requirements.txt
  - createdb bucketlist
env:
  - DB=postgres
addons:
  postgresql: "9.4"
script:
  - nosetests
notifications:
  slack: andela:
after_success:
  coveralls
